baseURL = "https://madargani.github.io/"
languageCode = "en-us"
title = "I'm not MAD"

[params]
  # favicon     = "img/favicon.png"
  description = "Andre Dargani's Personal Website"

  [params.author]
    name = 'Andre Dargani'

[module]
[[module.imports]]
path = "github.com/hugo-porto/theme"
