baseURL = "https://madargani.github.io/"
title = "I'm MAD"

[menus]
  [[menus.main]]
    name = "aboutMe"
    url = "/aboutMe"
    weight = 10
  [[menus.main]]
    name = "projects"
    url = "/projects"
    weight = 20
  [[menus.main]]
    name = "devLogs"
    url = "/devlogs"
    weight = 30
  [[menus.main]]
    name = "linkedIn"
    url = "https://linkedin.com/in/andre-dargani"
  [[menus.main]]
    name = "gitHub"
    url = "https://github.com/madargani"

